# Generated by Django 5.2.14 on 2026-09-17 16:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareLedgerMonthlyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(max_length=7, unique=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_debits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month_key'],
            },
        ),
        migrations.CreateModel(
            name='SpareLedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('trans_type', models.CharField(choices=[('CREDIT', 'Credit (money in)'), ('DEBIT', 'Debit (money out)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cash_type', models.CharField(choices=[('BANK', 'Bank'), ('CASH', 'Cash')], default='CASH', max_length=20)),
                ('month_key', models.CharField(db_index=True, editable=False, max_length=7)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
