# Generated by Django 5.2.14 on 2026-09-17 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, unique=True)),
                ('make', models.CharField(default='Honda', max_length=50)),
                ('engine_capacity', models.CharField(blank=True, max_length=20)),
                ('pct_code', models.CharField(blank=True, max_length=20, verbose_name='PCT code')),
                ('item_code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_number', models.CharField(max_length=50, unique=True)),
                ('engine_number', models.CharField(max_length=50, unique=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='VIN')),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=30)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In stock'), ('SOLD', 'Sold')], default='IN_STOCK', max_length=20)),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motorcycles', to='inventory.productmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
