# Generated by Django 5.2.14 on 2026-09-18 05:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='date_sold',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Archived units are hidden from the default list but never deleted.'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='chassis_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='engine_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='purchase_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('IN_TRANSIT', 'In transit'), ('DAMAGED', 'Damaged')], db_index=True, default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='year',
            field=models.PositiveIntegerField(help_text='Manufacture year.', validators=[django.core.validators.MinValueValidator(1980)]),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motorcycles', to='inventory.stocklocation'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='purchase_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motorcycles', to='inventory.supplier'),
        ),
        migrations.AddIndex(
            model_name='motorcycle',
            index=models.Index(fields=['status', 'is_active'], name='inventory_m_status_0118eb_idx'),
        ),
    ]
