# Generated by Django 5.2.14 on 2026-09-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocklocation_supplier_remove_motorcycle_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='purchase_reference',
            field=models.CharField(blank=True, help_text="Supplier's purchase/delivery order number, e.g. from a manufacturer stock export.", max_length=100),
        ),
    ]
